name = "cloudflare-search"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "KV"
id = "295d0e7d9a334dd1a52a03003457b7d1"
